services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "bundle install && bin/rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    restart: "always"
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - type: tmpfs
        target: /app/tmp/pids/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
    networks:
      - default
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: "always"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      RAILS_ENV: development
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./tmp/rd:/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080

  unit-tests:
    <<: *app
    command: >
      bash -c "bundle exec rspec"
    ports:
      - "3002:3002"
    environment:
      RAILS_ENV: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
